// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'divorce.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Divorce _$$_DivorceFromJson(Map<String, dynamic> json) => _$_Divorce(
      id: json['id'] as int,
      created_at: json['created_at'] as String,
      office_ward: Ward.fromJson(json['office_ward'] as Map<String, dynamic>),
      husband_ward: Ward.fromJson(json['husband_ward'] as Map<String, dynamic>),
      wife_ward: Ward.fromJson(json['wife_ward'] as Map<String, dynamic>),
      witness_ward: Ward.fromJson(json['witness_ward'] as Map<String, dynamic>),
      court_type: json['court_type'] as String,
      court_decission_no: json['court_decission_no'] as String,
      court_decission_date: json['court_decission_date'] as String,
      married_registration_no: json['married_registration_no'] as String,
      married_date_bs: json['married_date_bs'] as String,
      married_date_ad: json['married_date_ad'] as String,
      children_with: json['children_with'] as String,
      husband_full_name_np: json['husband_full_name_np'] as String,
      husband_full_name_en: json['husband_full_name_en'] as String,
      husband_birth_date: json['husband_birth_date'] as String,
      husband_birth_registration_no:
          json['husband_birth_registration_no'] as String,
      husband_religion: json['husband_religion'] as String,
      husband_birth_country: json['husband_birth_country'] as String,
      husband_citizenship_no: json['husband_citizenship_no'] as String,
      husband_citizenship_date: json['husband_citizenship_date'] as String,
      husband_issued_date: json['husband_issued_date'] as String,
      husband_citizenship_country:
          json['husband_citizenship_country'] as String,
      husband_street_name: json['husband_street_name'] as String,
      husband_father_name_en: json['husband_father_name_en'] as String,
      husband_father_name_np: json['husband_father_name_np'] as String,
      husband_tole: json['husband_tole'] as String,
      husband_house_no: json['husband_house_no'] as String,
      husband_education_status: json['husband_education_status'] as String,
      husband_mother_tongue: json['husband_mother_tongue'] as String,
      husband_grand_father_en: json['husband_grand_father_en'] as String,
      husband_grand_father_np: json['husband_grand_father_np'] as String,
      husband_mother_name_en: json['husband_mother_name_en'] as String,
      husband_mother_name_np: json['husband_mother_name_np'] as String,
      husband_address: json['husband_address'] as String,
      wife_full_name_np: json['wife_full_name_np'] as String,
      wife_full_name_en: json['wife_full_name_en'] as String,
      wife_birth_date: json['wife_birth_date'] as String,
      wife_education_status: json['wife_education_status'] as String,
      wife_religion: json['wife_religion'] as String,
      wife_mother_tongue: json['wife_mother_tongue'] as String,
      wife_street_name: json['wife_street_name'] as String,
      wife_tole: json['wife_tole'] as String,
      wife_house_no: json['wife_house_no'] as String,
      wife_birth_country: json['wife_birth_country'] as String,
      wife_citizenship_country: json['wife_citizenship_country'] as String,
      wife_citizenship_no: json['wife_citizenship_no'] as String,
      wife_citizenship_date: json['wife_citizenship_date'] as String,
      wife_address: json['wife_address'] as String,
      wife_grand_father_en: json['wife_grand_father_en'] as String,
      wife_grand_father_np: json['wife_grand_father_np'] as String,
      wife_father_name_en: json['wife_father_name_en'] as String,
      wife_father_name_np: json['wife_father_name_np'] as String,
      wife_mother_name_en: json['wife_mother_name_en'] as String,
      wife_mother_name_np: json['wife_mother_name_np'] as String,
      witness_full_name_np: json['witness_full_name_np'] as String,
      witness_full_name_en: json['witness_full_name_en'] as String,
      witness_street_name: json['witness_street_name'] as String,
      witness_tole: json['witness_tole'] as String,
      witness_house_no: json['witness_house_no'] as String,
      witness_birth_country: json['witness_birth_country'] as String,
      witness_citizenship_country:
          json['witness_citizenship_country'] as String,
      witness_citizenship_no: json['witness_citizenship_no'] as String,
      witness_citizenship_date: json['witness_citizenship_date'] as String,
      witness_photo: json['witness_photo'] as String,
    );

Map<String, dynamic> _$$_DivorceToJson(_$_Divorce instance) =>
    <String, dynamic>{
      'id': instance.id,
      'created_at': instance.created_at,
      'office_ward': instance.office_ward.toJson(),
      'husband_ward': instance.husband_ward.toJson(),
      'wife_ward': instance.wife_ward.toJson(),
      'witness_ward': instance.witness_ward.toJson(),
      'court_type': instance.court_type,
      'court_decission_no': instance.court_decission_no,
      'court_decission_date': instance.court_decission_date,
      'married_registration_no': instance.married_registration_no,
      'married_date_bs': instance.married_date_bs,
      'married_date_ad': instance.married_date_ad,
      'children_with': instance.children_with,
      'husband_full_name_np': instance.husband_full_name_np,
      'husband_full_name_en': instance.husband_full_name_en,
      'husband_birth_date': instance.husband_birth_date,
      'husband_birth_registration_no': instance.husband_birth_registration_no,
      'husband_religion': instance.husband_religion,
      'husband_birth_country': instance.husband_birth_country,
      'husband_citizenship_no': instance.husband_citizenship_no,
      'husband_citizenship_date': instance.husband_citizenship_date,
      'husband_issued_date': instance.husband_issued_date,
      'husband_citizenship_country': instance.husband_citizenship_country,
      'husband_street_name': instance.husband_street_name,
      'husband_father_name_en': instance.husband_father_name_en,
      'husband_father_name_np': instance.husband_father_name_np,
      'husband_tole': instance.husband_tole,
      'husband_house_no': instance.husband_house_no,
      'husband_education_status': instance.husband_education_status,
      'husband_mother_tongue': instance.husband_mother_tongue,
      'husband_grand_father_en': instance.husband_grand_father_en,
      'husband_grand_father_np': instance.husband_grand_father_np,
      'husband_mother_name_en': instance.husband_mother_name_en,
      'husband_mother_name_np': instance.husband_mother_name_np,
      'husband_address': instance.husband_address,
      'wife_full_name_np': instance.wife_full_name_np,
      'wife_full_name_en': instance.wife_full_name_en,
      'wife_birth_date': instance.wife_birth_date,
      'wife_education_status': instance.wife_education_status,
      'wife_religion': instance.wife_religion,
      'wife_mother_tongue': instance.wife_mother_tongue,
      'wife_street_name': instance.wife_street_name,
      'wife_tole': instance.wife_tole,
      'wife_house_no': instance.wife_house_no,
      'wife_birth_country': instance.wife_birth_country,
      'wife_citizenship_country': instance.wife_citizenship_country,
      'wife_citizenship_no': instance.wife_citizenship_no,
      'wife_citizenship_date': instance.wife_citizenship_date,
      'wife_address': instance.wife_address,
      'wife_grand_father_en': instance.wife_grand_father_en,
      'wife_grand_father_np': instance.wife_grand_father_np,
      'wife_father_name_en': instance.wife_father_name_en,
      'wife_father_name_np': instance.wife_father_name_np,
      'wife_mother_name_en': instance.wife_mother_name_en,
      'wife_mother_name_np': instance.wife_mother_name_np,
      'witness_full_name_np': instance.witness_full_name_np,
      'witness_full_name_en': instance.witness_full_name_en,
      'witness_street_name': instance.witness_street_name,
      'witness_tole': instance.witness_tole,
      'witness_house_no': instance.witness_house_no,
      'witness_birth_country': instance.witness_birth_country,
      'witness_citizenship_country': instance.witness_citizenship_country,
      'witness_citizenship_no': instance.witness_citizenship_no,
      'witness_citizenship_date': instance.witness_citizenship_date,
      'witness_photo': instance.witness_photo,
    };
